# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell" do |s|
    # Reset your pub key path 
    ssh_pub_key = nil
    begin
      # try Windows location
      ssh_pub_key = File.readlines("C:/Users/sanket/.ssh/id_rsa.pub").first.strip
    rescue Errno::ENOENT
      begin
        # try Linux default
        ssh_pub_key = File.readlines(File.expand_path("~/.ssh/id_rsa.pub")).first.strip
      rescue Errno::ENOENT
        puts "ERROR: SSH public key not found in either location"
      end
    end
    s.inline = <<-SHELL
    mkdir /root/.ssh
    touch /root/.ssh/authorized_keys
    echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end

  NodeCount = 3

  (1..NodeCount).each do |i|

    config.vm.define "ubuntuvm#{i}" do |node|

      node.vm.box               = "ubuntu/jammy64"
      node.vm.box_check_update  = false
      node.vm.box_version       = "20241002.0.0"
      node.vm.hostname          = "ubuntuvm#{i}.example.com"

      node.vm.network "private_network", ip: "10.0.2.10#{i}"

      node.vm.provider :virtualbox do |v|
        v.name    = "ubuntuvm#{i}"
        v.memory  = 3072
        v.cpus    = 2
      end

      node.vm.provider :libvirt do |v|
        v.nested  = true
        v.memory  = 2048
        v.cpus    = 2
      end

    end

  end

end
